import { GoogleGenAI } from '@google/genai';
import { NextResponse } from 'next/server';

export const runtime = 'edge';

const SYSTEM_PROMPT = `You are a deterministic QA Automation Execution Planner. Your sole purpose is to convert a Web Page Layout (provided in clean Markdown) and a User Testing Goal into a rigid, sequential JSON array of automated browser actions.

CRITICAL LOCATOR RULES:
1. PRIORITIZE ATTRIBUTES: Always use \`id\`, \`data-test\`, \`data-testid\`, or \`name\` attributes if they exist in the Markdown (e.g., "#login-button" or "[data-test='login-button']"). These are the most resilient.
2. TEXT vs BUTTON FALLBACKS:
   - For submit buttons, if no ID exists, use the value attribute (e.g., \`input[value='Login']\`).
   - For text/search input fields, NEVER use the value attribute. Instead, prioritize the \`name\`, \`type\`, or \`placeholder\` attributes (e.g., \`input[name='search']\` or \`input[placeholder='Search Wikipedia']\`).
   - DO NOT use Playwright pseudo-classes like \`:has-text()\`. Use 100% valid native CSS selectors compatible with \`document.querySelector()\`.
3. SEARCH BAR EXECUTION: Modern search bars use JS dropdowns that block synthetic button clicks. When asked to search for something, DO NOT create a separate 'click' step for the search button. Instead, append "{enter}" to the end of your string in the 'fill' step (e.g., "Playwright (software){enter}").
4. Completely avoid brittle, deep, autogenerated, or positional CSS/XPath paths (e.g., "div > div > span > input").

SUPPORTED ACTIONS SCHEMA:
- "navigate": Opens a target URL. Requires a full URL string in the "value" field.
- "click": Simulates a human mouse click on the element. "value" field must be empty.
- "fill": Clears and types text into an input field. Requires the string payload in the "value" field.
- "assertVisible": Verifies that a specific element exists and is rendered on the page. "value" field must be empty.
- "assertText": Verifies that a specific element contains the expected text string. Requires the expected text string in the "value" field.
- "assertUrl": Verifies that the current browser URL matches or contains the expected URL string. Locator field must be empty. Requires the expected URL string in the "value" field.

Your response must strictly conform to a JSON object containing a "steps" key whose value is an array of objects following this TypeScript interface:
interface PlaywrightJsonStep {
  action: "navigate" | "click" | "fill" | "assertVisible" | "assertText" | "assertUrl";
  locator: string; // The precise native document.querySelector() string or a highly specific CSS path (leave empty for assertUrl)
  value: string;   // The text payload (used for 'fill', 'navigate', 'assertText', and 'assertUrl')
  description: string; // A clean, natural language explanation of what this automation step is physically doing
}

OUTPUT CONSTRAINT:
Output ONLY a raw, valid JSON object matching the format: { "steps": [...] }. Do not include conversational filler, notes, or markdown fences. Start your response directly with '{' and end with '}'.`;

export async function POST(req: Request) {
  try {
    const { url, prompt } = await req.json();

    if (!url || !prompt) {
      return NextResponse.json(
        { error: 'Missing target URL or testing goal prompt.' },
        { status: 400 }
      );
    }

    // 1. Fetch the semantic markdown of the target URL using Jina Reader API
    const jinaUrl = `https://r.jina.ai/${url.trim()}`;
    const headers: Record<string, string> = {
      'Accept': 'text/plain'
    };
    if (process.env.JINA_API_KEY) {
      headers['Authorization'] = `Bearer ${process.env.JINA_API_KEY}`;
    }
    const jinaRes = await fetch(jinaUrl, {
      method: 'GET',
      headers
    });

    if (!jinaRes.ok) {
      const errorMsg = await jinaRes.text();
      return NextResponse.json(
        { error: `Jina Reader failed: ${jinaRes.status} ${errorMsg}` },
        { status: 502 }
      );
    }

    const pageMarkdown = await jinaRes.text();

    // 2. Call the Google Gemini API completion
    const geminiApiKey = process.env.GEMINI_API_KEY;
    if (!geminiApiKey) {
      return NextResponse.json(
        { error: 'Gemini API Key is not configured on the server.' },
        { status: 500 }
      );
    }

    const ai = new GoogleGenAI({ apiKey: geminiApiKey });

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-lite',
      contents: `Target Layout Markdown:\n${pageMarkdown}\n\nUser Goal:\n${prompt}`,
      config: {
        systemInstruction: SYSTEM_PROMPT,
        responseMimeType: 'application/json',
        temperature: 0.1,
      }
    });

    const rawContent = response.text || '';

    // Robust parsing of the JSON array from response content
    let cleanText = rawContent.trim();
    
    // Remove markdown code fences if present (e.g. ```json ... ```)
    if (cleanText.startsWith('```')) {
      cleanText = cleanText.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '');
    }
    cleanText = cleanText.trim();

    let steps: any[] = [];
    try {
      const parsed = JSON.parse(cleanText);
      if (Array.isArray(parsed)) {
        steps = parsed;
      } else if (parsed && typeof parsed === 'object') {
        // If the model wrapped the array in an object (e.g., { "steps": [...] } or { "actions": [...] })
        if (Array.isArray(parsed.steps)) {
          steps = parsed.steps;
        } else if (Array.isArray(parsed.actions)) {
          steps = parsed.actions;
        } else {
          // Look for any array property in the object
          const arrayKey = Object.keys(parsed).find(key => Array.isArray(parsed[key]));
          if (arrayKey) {
            steps = parsed[arrayKey];
          } else {
            throw new Error('No array found in JSON object');
          }
        }
      } else {
        throw new Error('Parsed result is not an array or object');
      }
    } catch (e: any) {
      console.error('JSON parsing failed. Raw response:', rawContent);
      return NextResponse.json(
        {
          error: 'Failed to parse deterministic JSON from LLM response.',
          rawResponse: rawContent,
          parseError: e.message
        },
        { status: 500 }
      );
    }

    return NextResponse.json({ steps });
  } catch (error: any) {
    console.error('Error in /api/generate:', error);
    return NextResponse.json(
      { error: error.message || 'Internal Server Error' },
      { status: 500 }
    );
  }
}
